### ISSUE TITLE
Finvader not working

### ISSUE THREAD

**Issue by king2206** [PetrKorab/FinVADER#1]
Hello,

I am very grateful for the code. However, I always get error when defining the function as provided:

`def finvader(text = 'str',                    # Text
             indicator = 'str',               # VADER' indicator: 'pos'/'neg'/'neu'/'compound' 
             use_sentibignomics: bool= False, # Use SentiBignomics lexicon
             use_henry: bool= False):         # Use Henry's lexicon
) `

Here is the error message : 
` File "<stdin>", line 5
    )
    ^
SyntaxError: unmatched ')'`

Please I need help for his issue.

**Comment by PetrKorab** [comment]
Hi @king2206,

I updated the README. Can you use the classifier now ?
